name: Build RISC-V-Trace-Connectors.pdf

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      # Step 2: Pull the latest RISC-V Docs container image
      - name: Pull Container
        run: docker pull riscvintl/riscv-docs-base-container-image:latest

      # Step 3: Build Files
      - name: Build Files
        run: cd ./docs && make RISC-V-Trace-Connectors.pdf

      # Step 4: Upload the built PDF files as independent artifacts
      - name: Upload RISC-V-Trace-Control-Interface PDF
        uses: actions/upload-artifact@v3
        with:
          name: RISC-V-Trace-Control-Interface
          path: ${{ github.workspace }}/docs/RISC-V-Trace-Connectors.pdf
          retention-days: 7
